= Metanorma stepmod2mn

image:https://github.com/metanorma/stepmod2mn/workflows/ubuntu/badge.svg["Build Status", link="https://github.com/metanorma/stepmod2mn/actions?workflow=ubuntu"]
image:https://github.com/metanorma/stepmod2mn/workflows/macos/badge.svg["Build Status", link="https://github.com/metanorma/stepmod2mn/actions?workflow=macos"]
image:https://github.com/metanorma/stepmod2mn/workflows/windows/badge.svg["Build Status", link="https://github.com/metanorma/stepmod2mn/actions?workflow=windows"]

== Installing Build Tools

You will need the `maven` build tool and `make`.

* https://www.baeldung.com/install-maven-on-windows-linux-mac[How to install Maven on Windows, Linux, Mac]


== Usage

convert specified xml file into adoc format and save it to data/resource_docs/draughting_elements/resource.adoc:

[source,sh]
----
java -jar target/stepmod2mn-1.10.jar <XML-FileName>
----

or save it to specified path:

[source,sh]
----
java -jar target/stepmod2mn-1.10.jar <XML-FileName> --output <ADOC-FileName>
----

generate SVG images in the tree data/:

[source,sh]
----
java -jar target/stepmod2mn-1.10.jar <start folder to process xml maps files> --svg
----

generate SVG image for Express Imagemap XML and Image:

[source,sh]
----
java -jar stepmod2mn-1.10.jar --xml <Express Imagemap XML file path> --image <Image file name> [--svg <resulted SVG map file or folder>]
----

e.g.

[source,sh]
----
java -jar target/stepmod2mn-1.10.jar data/resource_docs/draughting_elements/resource.xml 
----

[source,sh]
----
java -jar target/stepmod2mn-1.10.jar data/ --svg
----

[source,sh]
----
java -jar stepmod2mn-1.10.jar --xml data\resource_docs\fundamentals_of_product_description_and_support\schema_diagexpg1.xml --image schema_diagexpg1.gif --svg schema_diagexpg1.svg
----


== Building the package

[source,sh]
----
make all
----


== Releasing a new version

Update version in `pom.xml`, e.g.:

[source,xml]
----
<groupId>org.metanorma</groupId>
<artifactId>stepmod2mn</artifactId>
<version>1.10</version>
<name>STEPmod XML to Metanorma AsciiDoc converter</name>
----

Build the package using instructions above, the package will be created at:
`target/stepmod2mn-{version}.jar`

Tag the same version in Git:

[source,xml]
----
git tag v1.10
git push origin v1.10
----

Then the corresponding GitHub release will be automatically created at:
https://github.com/metanorma/stepmod2mn/releases

And downloadable at:
`https://github.com/metanorma/stepmod2mn/releases/download/v{version}/stepmod2mn-{version}.jar`


== Testing

The testing environment utilizes these tools:

* `make`


Running the tests:

[source,sh]
----
make test
----


== Copyright

Ribose Inc.
