= Metanorma stepmod2mn

image:https://github.com/metanorma/stepmod2mn/workflows/ubuntu/badge.svg["Build Status", link="https://github.com/metanorma/stepmod2mn/actions?workflow=ubuntu"]
image:https://github.com/metanorma/stepmod2mn/workflows/macos/badge.svg["Build Status", link="https://github.com/metanorma/stepmod2mn/actions?workflow=macos"]
image:https://github.com/metanorma/stepmod2mn/workflows/windows/badge.svg["Build Status", link="https://github.com/metanorma/stepmod2mn/actions?workflow=windows"]

== Installing Build Tools

You will need the `maven` build tool and `make`.

* https://www.baeldung.com/install-maven-on-windows-linux-mac[How to install Maven on Windows, Linux, Mac]


== Usage

=== Convert specified single XML into the Metanorma AsciiDoc format and save it in the source XML folder:

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <XML-FileName>
----

e.g. 

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar data/resource_docs/draughting_elements/resource.xml 
----

NOTE: resulted AsciiDoc found in data/resource_docs/draughting_elements/document.adoc


=== Convert specified single XML into the Metanorma AsciiDoc format and save it to the specified file/folder:

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <XML-FileName> [--output <AsciiDoc-FileName>]
----

e.g. 

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar data/resource_docs/draughting_elements/resource.xml --output result_dir/draughting_elements/document.adoc
----

=== Convert all resource.xml and module.xml in the specified folder and sub-folders into the Metanorma AsciiDoc format:

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <Input-folder>
----

e.g. 

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar data/
----

NOTE: the result AsciiDocs will be saved in the folder with the source resource.xml and module.xml files.


=== Convert all resource.xml and module.xml in the specified folder and sub-folders into the Metanorma AsciiDoc format and save them into the output folder:

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <Input-folder> [--output <Output-folder>]
----

e.g. 

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar data/ --output documents/
----


=== Convert all resource.xml and module.xml in the specified folder and sub-folders into the Metanorma AsciiDoc format, except specified documents:

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <Input-folder> [--exclude <documents list>]
----

e.g. 

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar data/ --exclude "machining_features"
----

=== Convert only specified documents resource.xml and module.xml in the specified folder and sub-folders into the Metanorma AsciiDoc format:

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <Input-folder> [--include-only <documents list>]
----

e.g. 

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar data/ --include-only "fundamentals_of_product_description_and_support kinematics"
----

=== Generate Metanorma collection files (metanorma.yml and collection.yml) for the documents specified in the publication index xml file in the tags 'resource_docs' and 'modules':

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <Publication-Index-XML-FileName>
----

e.g.

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar publication/part1000/CR_PMI_5/publication_index.xml
----

NOTE: the Metanorma collection files .yml will be saved in the 3 level up folder (usually, source repository's root folder).

=== Generate Metanorma collection files (metanorma.yml and collection.yml) for the documents specified in the publication index xml file in the tags 'resource_docs' and 'modules',
and save them into the output folder:

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <Publication-Index-XML-FileName> [--output <Output-folder>]
----

e.g.

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar iso-10303-srl/iso-10303-stepmod-wg12/publication/part1000/CR_PMI_5/publication_index.xml --output iso-10303-srl/
----

NOTE: the output folder should contains the folder with the generated .adoc (usually, 'documents'). You can specify this folder obviously by the parameter '--input-documents':

e.g.

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar iso-10303-srl/iso-10303-stepmod-wg12/publication/part1000/CR_PMI_5/publication_index.xml --output iso-10303-srl/CR_PMI_5 --input-documents iso-10303-srl/documents
----

NOTE: the Metanorma collection files (.yml) will be saved in the folder 'iso-10303-srl/CR_PMI_5' and the references point to the documents in the folder iso-10303-srl/documents.


=== Generate Metanorma collection files (metanorma.yml and collection.yml) for the specified type of the document (resource_docs or modules) in the publication index xml file:

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar <Publication-Index-XML-FileName> [--type <resource_docs or modules>]
----

e.g.

[source,sh]
----
java -Xss5m -jar target/stepmod2mn-1.43.jar publication/part1000/CR_PMI_5/publication_index.xml --type resource_docs
----

NOTE: the Metanorma collection file 'metanorma.yml' will be saved in the 3 level up folder (usually, source repository's root folder).


=== Generate SVG images in the specified folder and sub-folders:

[source,sh]
----
java -jar target/stepmod2mn-1.43.jar <start folder to process xml maps files> --svg
----

e.g. 

[source,sh]
----
java -jar target/stepmod2mn-1.43.jar data/resources --svg
----

=== Generate SVG images for the XML in the specified folder and sub-folders, and save them in the output folder:

[source,sh]
----
java -jar target/stepmod2mn-1.43.jar <start folder to process xml maps files> --svg [--output <Output-folder>]
----

e.g. 

[source,sh]
----
java -jar target/stepmod2mn-1.43.jar data/resources --svg --output schemas/
----

=== Generate SVG image for Express Imagemap XML and Image:

[source,sh]
----
java -jar stepmod2mn-1.43.jar --xml <Express Imagemap XML file path> --image <Image file name> [--svg <resulted SVG map file or folder>]
----

e.g.

[source,sh]
----
java -jar stepmod2mn-1.43.jar --xml data\resource_docs\fundamentals_of_product_description_and_support\schema_diagexpg1.xml --image schema_diagexpg1.gif --svg schema_diagexpg1.svg
----


== Building the package

[source,sh]
----
make all
----


== Releasing a new version

Update version in `pom.xml`, e.g.:

[source,xml]
----
<groupId>org.metanorma</groupId>
<artifactId>stepmod2mn</artifactId>
<version>1.43</version>
<name>STEPmod XML to Metanorma AsciiDoc converter</name>
----

Build the package using instructions above, the package will be created at:
`target/stepmod2mn-{version}.jar`

Tag the same version in Git:

[source,xml]
----
git tag v1.43
git push origin v1.43
----

Then the corresponding GitHub release will be automatically created at:
https://github.com/metanorma/stepmod2mn/releases

And downloadable at:
`https://github.com/metanorma/stepmod2mn/releases/download/v{version}/stepmod2mn-{version}.jar`


== Testing

The testing environment utilizes these tools:

* `make`


Running the tests:

[source,sh]
----
make test
----


== Copyright

Ribose Inc.
